
# category;

GET http://localhost:8000/categories/

###
GET http://localhost:8000/categories/30



###
POST http://localhost:8000/categories/
content-Type: application/json

{
    "name" : "all",
    "slug" : "star",
    "imageUrl" : "" 
}



###
DELETE http://localhost:8000/categories/29


###
PUT  http://localhost:8000/categories/36
Content-Type: application/json

{
    
    "name" : "12345678",
    "slug" : "123456789",
    "imageUrl" : "dasd" 
}


# product


###
GET http://localhost:8000/products/

###
GET http://localhost:8000/products/2



###
POST http://localhost:8000/products/
content-Type: application/json

{
    "name" : "das",
    "slug" : "34das",
    "imageUrl" : "" 
}



###
DELETE http://localhost:8000/products/15


###
PUT  http://localhost:8000/products/
Content-Type: application/json

{
    
    "name" : "12345678",
    "slug" : "123456789",
    "imageUrl" : "dasd" 
}





# user


###
GET http://localhost:8000/users/


###
GET http://localhost:8000/users/VImOe4S_Lcp-hYyAg5SD1



###
POST http://localhost:8000/users/
content-type: application/json

{
    "firstName":"Temuulendad",
    "lastName": "Bayrsaikhandad",
    "birthDate" : "1999-01-12",
    "email": "temvvlen121d1@gmail.com",
    "phone": "86911111",
    "password": "",
    "imageUrl": ""
}

###
DELETE http://localhost:8000/users/XWiuW5351EiX7M5LzfdbO

###
PUT  http://localhost:8000/users/VImOe4S_Lcp-hYyAg5SD1  
content-type: application/json

{
    "firstName":"hahaha",
    "lastName": "ahaahahahaa",
    "birthDate" : "1998-02-22",
    "email": "hakaanukup@gmail.com",
    "phone": "12345678",
    "password": "",
    "imageUrl": ""
}





